<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Noel Libiran | Portfolio</title>
  <style>
    :root {
      --primary: #007acc;
      --bg: #f9f9f9;
      --text: #333;
    }
    body {
      font-family: 'Segoe UI', sans-serif;
      margin: 0;
      background: var(--bg);
      color: var(--text);
      scroll-behavior: smooth;
    }
    header {
      background: var(--primary);
      color: #fff;
      padding: 2rem;
      text-align: center;
    }
    nav a {
      color: #fff;
      margin: 0 15px;
      text-decoration: none;
    }
    section {
      padding: 3rem 1.5rem;
      max-width: 900px;
      margin: auto;
    }
    h1, h2 {
      color: var(--primary);
    }
    .projects a {
      display: block;
      margin-bottom: 0.5rem;
      color: var(--primary);
      text-decoration: none;
    }
    footer {
      text-align: center;
      padding: 2rem;
      background: #eee;
      font-size: 0.9rem;
    }
    @media (min-width: 600px) {
      nav {
        display: flex;
        justify-content: center;
        gap: 20px;
      }
    }
  </style>
</head>
<body>
  <header>
    <h1>Noel Libiran</h1>
    <p>Customer Service | Data Management | ESL Instructor</p>
    <nav>
      <a href="#about">About</a>
      <a href="#education">Education</a>
      <a href="#skills">Skills</a>
      <a href="#projects">Projects</a>
      <a href="#contact">Contact</a>
    </nav>
  </header>

  <section id="about">
    <h2>About Me</h2>
    <p>
      I'm a 20-year-old irregular student with experience in customer service and education. 
      I’ve worked in fast food, gained hands-on teamwork skills, and also served as an ESL teacher.
      Passionate about learning, always seeking new opportunities to grow and expand my knowledge.
    </p>
  </section>

  <section id="education">
    <h2>Education</h2>
    <ul>
      <li><strong>College:</strong> Bachelor of Science in Information System (CCA)</li>
      <li><strong>Senior High:</strong> Angeles City Senior High School</li>
      <li><strong>High School:</strong> F.G. Nepomuceno Memorial High School</li>
      <li><strong>Elementary:</strong> Pineda Gutierrez Elementary School</li>
    </ul>
  </section>

  <section id="skills">
    <h2>Skills</h2>
    <ul>
      <li>Customer Service</li>
      <li>Microsoft Excel / Power Query</li>
      <li>Data Cleaning & Transformation</li>
      <li>English Communication & Tutoring</li>
      <li>Team Collaboration</li>
    </ul>
  </section>

  <section id="projects">
    <h2>Projects</h2>
    <div class="projects">
      <a href="#">Midterm Task 1: Data Cleaning with Excel</a>
      <a href="#">Midterm Task 2: Power Query Transformations</a>
      <a href="#">Midterm Task 3: Pivot Tables and Dashboard</a>
      <a href="#">Final Task 1: Events Management DB</a>
      <a href="#">Final Task 2: ER to Relational Tables</a>
      <a href="#">Final Task 3: Table Manipulation</a>
      <a href="#">Final Task 4: Employee Databases</a>
    </div>
  </section>

  <section id="contact">
    <h2>Contact</h2>
    <p>Email: <a href="mailto:your.nlibiran23-0472@cca.edu.ph">your.nlibiran23-0472@cca.edu.ph</a></p>
    <p>GitHub: <a href="https://github.com/Blooper1209" target="_blank">github.com/Blooper1209</a></p>
  </section>

  <footer>
    <p>© 2025 Noel Libiran. Hosted on GitHub Pages.</p>
  </footer>
</body>
</html>
