title: Libiran Portfolio
logo : "C:\Users\edral\Downloads\411341023_3756543724580890_608549568412374930_n.jpg"
show_downloads: true
theme: jekyll-theme-minimal
remote_theme: pages-themes/modernist@v0.2.0
plugins: jekyll-theme-slate
